import { storySymbols } from "./marketNewsRanking.js";

const MINUTE = 60_000;
const finite = (value) => value == null || value === "" || !Number.isFinite(Number(value)) ? null : Number(value);
const date = (time) => new Date(time).toLocaleDateString("sv-SE", { timeZone: "Europe/Stockholm" });
const minuteOfDay = (time) => {
  const [hour, minute] = new Intl.DateTimeFormat("en-GB", { timeZone: "Europe/Stockholm", hour: "2-digit", minute: "2-digit", hourCycle: "h23" }).format(time).split(":").map(Number);
  return hour * 60 + minute;
};
const regularWindow = (from, to) => date(from) === date(to) && minuteOfDay(from) >= 540 && minuteOfDay(to) <= 1050;

// One explicit company and publication/session match. A company-wide volume
// snapshot must never be presented as volume generated by this particular story.
export function newsMarketContext(item) {
  const context = item.marketContext;
  const symbols = storySymbols(item);
  if (!context || symbols.length !== 1 || context.symbol !== symbols[0]
    || context.storyId !== item.id || context.scope !== "session_context"
    || Date.parse(context.publishedAt) !== item.ts
    || !Number.isFinite(item.ts) || !Number.isFinite(context.asOf)
    || context.asOf <= item.ts || date(context.asOf) !== context.sessionDate
    || date(item.ts) !== context.sessionDate) return null;
  const ratio = (value) => finite(value) !== null && finite(value) >= 0 ? finite(value) : null;
  return { ...context, rvolAtTime: ratio(context.rvolAtTime), dailyRvol: ratio(context.dailyRvol) };
}

export function newsMarketAttention(item, now) {
  const none = { priceBoost: 0, volumeBoost: 0, total: 0, priceWindow: null, volumeMetric: null };
  const symbols = storySymbols(item);
  const reaction = item.reaction;
  const asOf = finite(reaction?.asOf);
  if (symbols.length !== 1 || !Number.isFinite(now) || !Number.isFinite(item.ts)
    || asOf === null || asOf <= item.ts || asOf > now || item.ts > now) return none;
  let pct = null, priceWindow = null;
  // Prefer a consistent completed window, not whichever return is largest.
  // Baseline provenance is still an upstream limitation documented in the audit.
  for (const [key, minutes] of [["h1Pct", 60], ["m15Pct", 15]]) {
    const end = item.ts + minutes * MINUTE;
    if (asOf >= end && regularWindow(item.ts, end) && finite(reaction[key]) !== null) {
      pct = finite(reaction[key]); priceWindow = key; break;
    }
  }
  if (pct === null && asOf - item.ts <= 4 * 60 * MINUTE
    && now - asOf <= 15 * MINUTE && date(asOf) === date(item.ts)
    && finite(reaction?.pct) !== null) {
    pct = finite(reaction.pct); priceWindow = "rolling";
  }
  if (pct === null) return none;
  const priceBoost = Math.min(Math.abs(pct) * 2, priceWindow === "rolling" ? 6 : 12);
  const context = newsMarketContext(item);
  let volumeMetric = null, ratio = null;
  // Suppress thin, stale or pre-publication context. Missing data is neutral.
  if (Math.abs(pct) >= 1 && context && context.asOf <= now && now - context.asOf <= 15 * MINUTE
    && finite(context.turnover) >= 1_000_000) {
    if (context.baselineMature === true && context.baselineSessionCount >= 20 && context.rvolAtTime !== null) {
      volumeMetric = "rvolAtTime"; ratio = context.rvolAtTime;
    } else if (minuteOfDay(context.asOf) >= 1050 && context.dailyRvol !== null) {
      volumeMetric = "dailyRvol"; ratio = context.dailyRvol;
    }
  }
  // These correlated ratios are alternatives, never two additive bonuses.
  const volumeBoost = ratio > 1 ? Math.min(8, Math.log2(ratio) * 4) : 0;
  return { priceBoost, volumeBoost, total: Math.min(20, priceBoost + volumeBoost), priceWindow, volumeMetric };
}

export const volumeRatioLabel = (value) => `${new Intl.NumberFormat("sv-SE", { maximumFractionDigits: 1 }).format(value)}×`;
