import { useEffect, useState } from "react";
import { pnlColor } from "../utils/utils";
import { fetchArticle } from "../utils/api";
import dayjs from "dayjs";
import ArticleComponent from "../components/ArticleComponent";
import PreviousArticle from "../components/PreviousArticle";
import { Link } from "react-router";
import { FaArrowDown } from "react-icons/fa";
import utc from "dayjs/plugin/utc"

export function meta() {
  return [
    { title: "Omxsum - Daily Stock Market Summary" },
    { name: "description", content: "Daily summary of the Swedish stock market generated by AI" },
  ];
}

export const loader = async () => {
  const article = await fetchArticle();
  return article;
};

export default function Home({ loaderData }) {
  const articles = loaderData

  if (!articles) {
    return <div className="text-text">Loading...</div>;
  }

  dayjs.extend(utc);

  const isTodaysArticle = dayjs(articles[0].createdAt).day() === dayjs.utc().day()

  return (
    <main className="min-h-screen bg-background  relative ">
      <header className=" w-full px-10 py-2 relative z-10 bg-foreground border-b border-border mb-8">
        <span className="text-xl text-border font-serif font-black italic pb-2">Omxsum</span>
        {/* <p className="text-lg text-text-muted mb-4 prose">Morningsum is a daily summary of the stock market focusing on the Swedish Market. The summary is generated by an LLM based on the latest market news and data. The summary is updated daily at 08:30 CEST</p> */}
      </header>


      {isTodaysArticle ? <ArticleComponent article={articles[0]} /> :
        <div className="min-h-[80vh] max-w-6xl flex flex-col justify-center items-center mx-auto px-4 py-4 mb-8  shadow-black border-border border-opacity-10">
          <h1 className="text-4xl font-bold text-text">{dayjs.utc().add("1", "hour").format("HH:mm")}</h1>
          <h2 className=" font-bold text-text-article text-base">Morgonbrevet släpps kl. 08.00</h2>
          <p className="text-text-muted mb-2">Läs gårdagens artiklar</p>
          <Link to="#prev" className="hover:text-accent"><FaArrowDown /></Link>
        </div>
      }


      <div className="max-w-6xl py- mx-auto px-4 relative z-10 mt-20 ">
        <div className="w-full mx-auto mt-8 relative z-10 border-b border-border">
          <h2 className="text-lg font-serif font-black text-text-muted italic mb-4 mt-8">Tidigare artiklar</h2>
        </div>
        <div className="w-full mx-auto mt-8 grid grid-cols-1 grid-rows-4 md:grid-cols-2 md:grid-rows-2 gap-4 relative z-10 " id="prev">
          {articles.slice(1).map((article, idx) => (
            <PreviousArticle key={idx} article={article} />
          ))}
        </div>
      </div>
      <footer className="w-full mx-auto px-8 py-4 mt-8 relative z-10 bg-[#010204] border-t border-border">
        <p className="text-text-muted text-sm">© 2025 Omxsum</p>
      </footer>
    </main>
  );
}