import { useEffect, useState } from "react";
import { pnlColor } from "../utils/utils";
import { fetchArticle } from "../utils/api";
import dayjs from "dayjs";
import ArticleComponent from "../components/ArticleComponent";

export function meta() {
  return [
    { title: "New React Router App" },
    { name: "description", content: "Welcome to React Router!" },
  ];
}

export default function Home() {
  const [articles, setArticles] = useState();

  useEffect(() => {
    const fetchData = async () => {
      try {
        const data = await fetchArticle();
        setArticles(data);
      } catch (error) {
        console.error("Error fetching data:", error);
      }
    };
    fetchData();
  }, []);

  if (!articles) {
    return <div>...</div>;
  }






  return (
    <main className="min-h-screen bg-gradient-to-br from-gray-100 to-gray-300 dark:from-gray-950 dark:to-gray-800 relative p-4">
      <div className="absolute inset-0 z-20 bg-[url(https://grainy-gradients.vercel.app/noise.svg)] opacity-20 pointer-events-none"></div>
      <header className="max-w-4xl mx-auto px-4 mt-8 relative z-10 border-b border-zinc-100 dark:border-zinc-950">
        <h1 className="text-4xl font-serif font-black text-zinc-800 dark:text-zinc-100 italic pb-2">Morningsum</h1>
        <p className="text-lg text-zinc-800 dark:text-zinc-400 mb-4 prose prose">Morningsum is a daily summary of the stock market focusing on the Swedish Market. The summary is generated by an LLM based on the latest market news and data. The summary is updated daily at 08:30 CEST</p>
      </header>
      <ArticleComponent article={articles[0]} />
      <div className="max-w-4xl mx-auto px-4 mt-8 relative z-10">
        <h2 className="text-2xl font-serif font-black text-zinc-600 dark:text-zinc-400 italic mb-4 mt-8">Previous Summaries</h2>
        {articles.slice(1).map((article, idx) => (
          <ArticleComponent key={idx} article={article} />
        ))}
      </div>


      <footer className="max-w-4xl mx-auto px-4 mt-8 relative z-10 ">
        <p className="text-zinc-400 dark:text-zinc-200 text-sm mb-4">© 2025 Morningsum</p>
      </footer>
    </main>


  )
}
