import { useEffect, useState } from "react";
import { pnlColor } from "../utils/utils";
import { fetchArticle } from "../utils/api";
import dayjs from "dayjs";
import ArticleComponent from "../components/ArticleComponent";
import PreviousArticle from "../components/PreviousArticle";
import { Link } from "react-router";
import { FaArrowDown, FaTwitter } from "react-icons/fa";
import utc from "dayjs/plugin/utc"
import { FaBluesky, FaX } from "react-icons/fa6";

export function meta() {
  return [
    { title: "OMXsum - Dagliga marknadssummeringar" },
    { name: "description", content: "Dagliga marknadssummeringar och viktiga pressmeddelanden från morgonens nyheter – genererade av AI varje dag kl. 08:00. Få en snabb överblick av den svenska börsen på OMXsum.com." },
  ];
}

export const loader = async () => {
  const article = await fetchArticle();
  return article;
};

export default function Home({ loaderData }) {
  const articles = loaderData
  dayjs.extend(utc);
  const [currentTime, setCurrentTime] = useState(dayjs.utc().add("1", "hour").format("HH:mm:ss"))

  if (!articles) {
    return <div className="text-text">Loading...</div>;
  }



  const isTodaysArticle = dayjs(articles[0].createdAt).day() === dayjs.utc().day()

  useEffect(() => {
    const timer = setInterval(() => {
      setCurrentTime(dayjs.utc().add(1, "hour").format("HH:mm:ss"))
    }, 500)

    return () => clearInterval(timer)
  }, [])

  return (
    <main className="min-h-screen bg-gradient-to-tr relative ">
      <header className=" w-full px-10 py-2 relative z-10 bg-foreground border-b border-border mb-8">
        <span className="text-xl text-border font-serif font-black italic pb-2">Omxsum</span>
        {/* <p className="text-lg text-text-muted mb-4 prose">Morningsum is a daily summary of the stock market focusing on the Swedish Market. The summary is generated by an LLM based on the latest market news and data. The summary is updated daily at 08:30 CEST</p> */}
      </header>


      {isTodaysArticle ? <ArticleComponent article={articles[0]} /> :
        <div className="min-h-[80vh] max-w-6xl flex flex-col justify-center items-center mx-auto px-4 py-4 mb-8  shadow-black border-border border-opacity-10">
          <h2 className="text-4xl font-bold text-text">{currentTime}</h2>
          <h3 className=" font-bold text-text-article text-base">Morgonbrevet släpps kl. 08.00</h3>
          <p className="text-text-muted mb-2">Läs gårdagens artiklar</p>
          <Link to="#prev" className="hover:text-secondary transition-colors"><FaArrowDown /></Link>
        </div>
      }


      <div className="max-w-6xl py- mx-auto px-4 relative z-10 mt-20 ">
        <div className="w-full mx-auto mt-8 relative z-10 border-b border-border">
          <h2 className="text-lg font-serif font-black text-text-muted italic mb-4 mt-8">Tidigare artiklar</h2>
        </div>
        <div className="w-full mx-auto mt-8 grid grid-cols-1 grid-rows-4 md:grid-cols-2 md:grid-rows-2 gap-4 relative z-10 " id="prev">
          {
            isTodaysArticle ? articles.slice(1).map((article, idx) => (
              <PreviousArticle key={idx} article={article} />
            )) :
              articles.map((article, idx) => (
                <PreviousArticle key={idx} article={article} />
              ))
          }
        </div>
      </div>
      <footer className="w-full mx-auto px-8 py-4 mt-8 flex flex-row items-center space-x-4 relative z-10 bg-[#010204] border-t border-border">
        <p className="text-text-muted text-sm">© 2025 Omxsum</p>
        <Link to="https://x.com/omxtamer" className="text-text-muted"><FaTwitter /></Link>
        <Link to="https://bsky.app/profile/karlbergg.bsky.social" className="text-text-muted"><FaBluesky /></Link>
        <p className="text-text-muted text-sm">Other projects: </p>
        <Link to="https://trademaxxer.com/about" className="text-sm text-text-muted hover:underline">Trademaxxer</Link>
      </footer>
    </main>
  );
}