import React from 'react'
import { Link, Outlet } from "react-router"
import EmailInput from "../components/EmailInput"
import { FaTwitter } from "react-icons/fa"
import { FaBluesky } from "react-icons/fa6"


export default function rootLayout() {
    return (
        <main className="min-h-screen bg-gradient-to-tr relative ">
            <header className=" w-full px-10 py-2 relative z-10 bg-foreground border-b border-border mb-8">
                <span className="text-xl text-border font-serif font-black italic pb-2">Omxsum</span>
                {/* <p className="text-lg text-text-muted mb-4 prose">Morningsum is a daily summary of the stock market focusing on the Swedish Market. The summary is generated by an LLM based on the latest market news and data. The summary is updated daily at 08:30 CEST</p> */}
            </header>
            <Outlet />
            <footer className="w-full mx-auto px-8 py-12 md:py-4 mt-8 flex flex-col md:flex-row items-center space-x-4 relative z-10 bg-[#010204] border-t border-border">
                <div className="flex flex-row items-center space-x-2 mb-2 md:mb-0">
                    <p className="text-text-muted text-sm border-r border-border pr-2">© 2025 Omxsum</p>
                    <p className="text-text-muted text-sm">Socialt: </p>
                    <Link to="https://x.com/omxtamer" className="text-text-muted"><FaTwitter /></Link>
                    <Link to="https://bsky.app/profile/karlbergg.bsky.social" className="text-text-muted border-r border-border pr-2"><FaBluesky /></Link>
                    <p className="text-text-muted text-sm">Other projects: </p>
                    <Link to="https://trademaxxer.com/about" className="text-sm text-text-muted hover:underline">Trademaxxer</Link>
                    <p></p>
                </div>
                <EmailInput />
            </footer>
        </main>
    )
}
