import React, { useContext } from 'react'
import { Link, Outlet } from "react-router"
import EmailInput from "../components/EmailInput"
import { FaTwitter } from "react-icons/fa"
import { FaBluesky, FaPerson } from "react-icons/fa6"
import { useModal } from "../providers/ModalProvider"
import { signUp } from "../utils/api"
import LogInModal from "../modals/logInModal"
import { useAuthContext } from "../providers/AuthProvider"
import { IoIosSettings } from "react-icons/io"

export function meta() {
    return [
        { title: "OMXsum - Dagliga marknadssummeringar" },
        { name: "description", content: "Dagliga marknadssummeringar och viktiga pressmeddelanden från morgonens nyheter – genererade av AI varje dag kl. 08:00. Få en snabb överblick av den svenska börsens nyheter på OMXsum.com." },
    ];
}


export default function rootLayout() {
    const { openModal } = useModal();
    const { user, isGuestUser } = useAuthContext();

    const handleOpenModal = () => {
        openModal(<LogInModal />);
    };

    if (!user) {
        return
    }

    return (
        <main className="min-h-screen relative ">
            <header className="flex  justify-center w-full px-10 py-4 bg-foreground border-b border-border mb-8">
                <div className="flex w-5/6 flex-col md:flex-row justify-between font-sans items-center space-x-2 relative z-10">
                    <div className="flex flex-row space-x-4 justify-between w-full md:w-fit items-center mb-2 md:mb-0">
                        <span className="text-xl text-text font-serif font-black italic pr-4 ">Omxsum</span>
                        <nav className="text-text-muted space-x-2 ">
                            <Link to="/" className={""}>Morgonbrevet</Link>
                            <Link to="/kvallsbrev" className={""}>Kvällsbrev</Link>
                            <Link to="/about" className={""}>Om</Link>
                            <Link to="/skanna" className="relative"><span>Skanna</span><span className="absolute font-bold -top-1 -right-4 ml-1 px-1 bg-secondary text-white text-xs rounded-full">+</span></Link>
                        </nav>
                    </div>
                    {/* <p className="text-lg text-text-muted mb-4 prose">Morningsum is a daily summary of the stock market focusing on the Swedish Market. The summary is generated by an LLM based on the latest market news and data. The summary is updated daily at 08:30 CEST</p> */}
                    <div className="hidden md:flex flex-row items-center space-x-2">
                        {isGuestUser ? (
                            <button className="hover:underline cursor-pointer" onClick={handleOpenModal}>Logga in</button>
                        ) : (
                            <>
                                <Link to="/settings" className="text-xl text-text-muted cursor-pointer" ><IoIosSettings /></Link>
                                <span className="text-sm text-text-muted">{user.email}</span>
                            </>

                        )}
                    </div>
                </div>
                {/* <span className="text-text-muted"><span className="text-secondary">Nytt:</span> Registrera dig för mailutskick!</span> */}
            </header>
            <Outlet />
            <footer className="w-full mx-auto px-8 py-12 md:py-4 mt-8 flex flex-col md:flex-row items-center space-x-4 relative z-10 bg-[#010204] border-t border-border">
                <div className="flex flex-row items-center space-x-2 mb-2 md:mb-0">
                    <p className="text-text-muted text-sm border-r border-border pr-2">© 2025 Omxsum</p>
                    <p className="text-text-muted text-sm">Socialt: </p>
                    <Link to="https://x.com/omxtamer" className="text-text-muted"><FaTwitter /></Link>
                    <Link to="https://bsky.app/profile/karlbergg.bsky.social" className="text-text-muted border-r border-border pr-2"><FaBluesky /></Link>
                    <p className="text-text-muted text-sm">Other projects: </p>
                    <Link to="https://trademaxxer.com/about" className="text-sm text-text-muted hover:underline">Trademaxxer</Link>
                    <p></p>
                </div>
                <EmailInput />
            </footer>
        </main>
    )
}
